"""Render files/CV_Nie.pdf to PNGs in images/cv/ for inline display on /cv/.

Inline <embed>/<iframe> PDF viewing depends on the visitor's browser having a
PDF plugin enabled; when it doesn't (Chrome set to download PDFs, some
extensions, older mobile browsers) the frame renders blank with no error and
no fallback. Rendering to images at build time always works.

Requires poppler:  brew install poppler

    uv run python cv_render.py
"""

import shutil
import subprocess
import sys
from pathlib import Path

PDF = Path("files/CV_Nie.pdf")
OUT_DIR = Path("images/cv")
PAGE_MD = Path("_pages/cv.md")
DPI = 200  # crisp on retina at ~800px display width

BEGIN = "<!-- BEGIN generated by cv_render.py -->"
END = "<!-- END generated by cv_render.py -->"


def require(tool: str) -> None:
    if shutil.which(tool) is None:
        sys.exit(f"error: {tool} not found. Install poppler:  brew install poppler")


def page_count(pdf: Path) -> int:
    out = subprocess.run(
        ["pdfinfo", str(pdf)], capture_output=True, text=True, check=True
    ).stdout
    for line in out.splitlines():
        if line.startswith("Pages:"):
            return int(line.split(":")[1])
    sys.exit("error: could not read page count from pdfinfo")


def render(pdf: Path, out_dir: Path) -> list[Path]:
    if out_dir.exists():
        for old in out_dir.glob("page-*.png"):
            old.unlink()
    out_dir.mkdir(parents=True, exist_ok=True)
    subprocess.run(
        ["pdftoppm", "-png", "-r", str(DPI), str(pdf), str(out_dir / "page")],
        check=True,
    )
    return sorted(out_dir.glob("page-*.png"))


def build_markup(pages: list[Path], n_expected: int) -> str:
    if len(pages) != n_expected:
        sys.exit(f"error: rendered {len(pages)} images, expected {n_expected}")

    imgs = "\n".join(
        f'  <img src="{{{{ \'/{p.as_posix()}\' | relative_url }}}}" '
        f'alt="Curriculum Vitae, page {i} of {len(pages)}" loading="lazy">'
        for i, p in enumerate(pages, start=1)
    )

    return f"""{BEGIN}
<p class="cv-actions">
  <a href="{{{{ '/{PDF.as_posix()}' | relative_url }}}}" target="_blank" rel="noopener">Open the PDF</a> &middot;
  <a href="{{{{ '/{PDF.as_posix()}' | relative_url }}}}" download>Download PDF</a>
</p>

<div class="cv-pages">
{imgs}
</div>

<style>
.cv-actions {{ margin-bottom: 1em; font-size: 0.85em; }}
.cv-pages img {{
  display: block;
  width: 100%;
  height: auto;
  margin-bottom: 1.25em;
  border: 1px solid #ddd;
  box-shadow: 0 1px 4px rgba(0, 0, 0, 0.12);
}}
</style>
{END}"""


def splice(page: Path, markup: str) -> None:
    text = page.read_text()
    if BEGIN in text and END in text:
        head, rest = text.split(BEGIN, 1)
        _, tail = rest.split(END, 1)
        page.write_text(head + markup + tail)
    else:
        sys.exit(
            f"error: {page} is missing the {BEGIN} / {END} markers. "
            "Add them where the CV should render."
        )


def main() -> None:
    require("pdftoppm")
    require("pdfinfo")
    if not PDF.exists():
        sys.exit(f"error: {PDF} not found")

    n = page_count(PDF)
    pages = render(PDF, OUT_DIR)
    splice(PAGE_MD, build_markup(pages, n))
    print(f"Rendered {len(pages)} page(s) at {DPI} dpi -> {OUT_DIR}/")
    print(f"Updated {PAGE_MD}")


if __name__ == "__main__":
    main()
