"""Shrink oversized images in files/pics/ and images/ so pages load fast.

- The profile photo (author avatar, loaded on every page) is resized to
  AVATAR_WIDTH px wide.
- Any other JPEG over MIN_BYTES is resized in place to at most MAX_PX on its
  long side at JPEG quality QUALITY. Filenames don't change, so no links break.
- Any PNG over MIN_BYTES is converted to a .jpg next to it (transparent areas
  flattened onto white, the page background), the .png is deleted, and every
  reference in the site source is rewritten to the new name.

Safe to re-run: files already under the limits are skipped. Originals remain
in git history. JPEGs go through macOS `sips` (keeps EXIF orientation); PNGs
through Pillow.

    uv run python image_optimize.py            # do it
    uv run python image_optimize.py --dry-run  # just list what would change
"""

import shutil
import subprocess
import sys
from pathlib import Path

from PIL import Image

DIRS = [Path("files/pics"), Path("images")]
SKIP_DIRS = [Path("images/cv")]  # generated by cv_render.py
AVATAR = Path("images/cheng-nie-2023-12-08-mugshot.jpg")
AVATAR_WIDTH = 400
MAX_PX = 1600
QUALITY = 80
MIN_BYTES = 500_000

JPEG_EXTS = {".jpg", ".jpeg"}
# Where image links live; _site/ is build output and is skipped.
SOURCE_DIRS = ["_posts", "_notes", "_pages", "_includes", "_layouts", "_data"]
SOURCE_EXTS = {".md", ".html", ".yml", ".yaml"}


def require(tool: str) -> None:
    if shutil.which(tool) is None:
        sys.exit(f"error: {tool} not found (this script needs macOS sips)")


def sips_props(path: Path) -> dict[str, str]:
    out = subprocess.run(
        ["sips", "-g", "pixelWidth", "-g", "pixelHeight", str(path)],
        capture_output=True, text=True, check=True,
    ).stdout
    props = {}
    for line in out.splitlines()[1:]:
        key, _, value = line.strip().partition(": ")
        props[key] = value
    return props


def to_jpeg(src: Path, dst: Path, *, max_px: int | None = None, width: int | None = None) -> None:
    cmd = ["sips", "-s", "format", "jpeg", "-s", "formatOptions", str(QUALITY)]
    if width:
        cmd += ["--resampleWidth", str(width)]
    elif max_px:
        cmd += ["-Z", str(max_px)]
    subprocess.run(cmd + [str(src), "--out", str(dst)], capture_output=True, check=True)


def png_to_jpeg(src: Path, dst: Path) -> None:
    with Image.open(src) as im:
        im = im.convert("RGBA")
        flat = Image.new("RGB", im.size, "white")
        flat.paste(im, mask=im.getchannel("A"))
        flat.thumbnail((MAX_PX, MAX_PX), Image.Resampling.LANCZOS)
        flat.save(dst, "JPEG", quality=QUALITY, optimize=True, progressive=True)


def candidates() -> list[Path]:
    files = []
    for d in DIRS:
        for p in sorted(d.rglob("*")):
            if not p.is_file() or any(s in p.parents for s in SKIP_DIRS):
                continue
            if p.suffix.lower() in JPEG_EXTS | {".png"} and p.stat().st_size > MIN_BYTES:
                files.append(p)
    return files


def rewrite_references(old: Path, new: Path) -> list[Path]:
    changed = []
    for d in SOURCE_DIRS:
        for f in Path(d).rglob("*"):
            if not f.is_file() or f.suffix not in SOURCE_EXTS:
                continue
            text = f.read_text()
            updated = text.replace(f"/{old.as_posix()}", f"/{new.as_posix()}")
            if updated != text:
                f.write_text(updated)
                changed.append(f)
    return changed


def main() -> None:
    require("sips")
    dry_run = "--dry-run" in sys.argv
    before = after = 0

    for p in candidates():
        size = p.stat().st_size
        props = sips_props(p)
        long_side = max(int(props["pixelWidth"]), int(props["pixelHeight"]))

        if p == AVATAR:
            if int(props["pixelWidth"]) <= AVATAR_WIDTH:
                continue
            print(f"avatar  {p}  {size / 1e6:.1f} MB")
            if not dry_run:
                to_jpeg(p, p, width=AVATAR_WIDTH)
        elif p.suffix.lower() in JPEG_EXTS:
            print(f"resize  {p}  {size / 1e6:.1f} MB, {long_side}px")
            if not dry_run:
                to_jpeg(p, p, max_px=MAX_PX)
        else:  # PNG
            new = p.with_suffix(".jpg")
            if new.exists():
                print(f"skip    {p}  ({new.name} already exists)")
                continue
            print(f"convert {p} -> {new.name}  {size / 1e6:.1f} MB, {long_side}px")
            if not dry_run:
                png_to_jpeg(p, new)
                p.unlink()
                for f in rewrite_references(p, new):
                    print(f"          updated link in {f}")
                p = new

        before += size
        after += size if dry_run else p.stat().st_size

    if not dry_run:
        print(f"\n{before / 1e6:.1f} MB -> {after / 1e6:.1f} MB")


if __name__ == "__main__":
    main()
